# Generated by Django 4.2.30 on 2026-09-27 04:50

import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("godaddy", "GoDaddy"),
                            ("cloudflare", "Cloudflare"),
                            ("aliyun", "Aliyun DNS"),
                            ("tencent", "Tencent Cloud DNS"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("api_base", models.URLField(blank=True, max_length=300)),
                ("credential_ciphertext", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_zone_count", models.PositiveIntegerField(default=0)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_accounts",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="provideraccount",
            constraint=models.UniqueConstraint(
                condition=Q(("is_default", True)),
                fields=("workspace",),
                name="one_default_provider_account_per_workspace",
            ),
        ),
    ]
